inherits: _base_llama31_8b.yaml

run_name: flashgrpo_fair_fastgrpo_b200_llama31_8b_gsm8k

data:
  train_option: gsm8k

training:
  saved_model_dir: outputs/flashgrpo_fair_fastgrpo_b200_llama31_8b_gsm8k/target_lora
  saved_medusa_dir: outputs/flashgrpo_fair_fastgrpo_b200_llama31_8b_gsm8k/medusa_heads

logging:
  log_dir: logs/flashgrpo_fair_fastgrpo_b200/llama31_8b_gsm8k

