inherits: _base_qwen25_7b.yaml

run_name: flashgrpo_fair_fastgrpo_b200_qwen25_7b_simplelr

data:
  train_option: simplelr_abel_level3to5

training:
  saved_model_dir: outputs/flashgrpo_fair_fastgrpo_b200_qwen25_7b_simplelr/target_lora
  saved_medusa_dir: outputs/flashgrpo_fair_fastgrpo_b200_qwen25_7b_simplelr/medusa_heads

logging:
  log_dir: logs/flashgrpo_fair_fastgrpo_b200/qwen25_7b_simplelr

